version: '2'
services:
  backend:
    build: ./backend
    ports:
      - '4444:4444'
    depends_on:
      - mongo
    networks:
      - webappnetwork
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge